server: 
  port: 8041
security:
  basic: 
    enabled: false
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring: 
  rabbitmq: 
    host: http://ec2-34-227-76-119.compute-1.amazonaws.com
    port: 5672
    username: guest
    password: guest
    
revature: 
  caliber: 
    service: 
      address: address
      assessment: assessment
      batch: batch
      category: category
      grade: grade
      note: note
      panel: panel
      salesforce: salesforce
      trainee: trainee
      trainer: trainer
      
