server:
  port: 8081

spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    pdf:
      path: /pdf/**
      serviceId: pdf
    types:
      path: /types/**
      serviceId: types
    trainer:
      path: /trainer/**
      serviceId: trainer
    assessment:
      path: /assessment/**
      serviceId: assessment
    salesforce:
      path: /salesforce/**
      serviceId: salesforce
    salesforce_all:
      path: /all/**
      serviceId: salesforce
  host:
    connect-timeout-millis: 300000
    socket-timeout-millis: 300000
